# Generated by Django 4.1.7 on 2023-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='number',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
