# Generated by Django 4.1.5 on 2023-01-11 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_status', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
